# -*- coding: utf-8 -*-
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmPrincipal(object):
    def setupUi(self, frmPrincipal):
        frmPrincipal.setObjectName("frmPrincipal")
        frmPrincipal.resize(1122, 626)
        self.centralwidget = QtWidgets.QWidget(frmPrincipal)
        self.centralwidget.setObjectName("centralwidget")
        self.grp_opciones = QtWidgets.QGroupBox(self.centralwidget)
        self.grp_opciones.setGeometry(QtCore.QRect(4, 3, 111, 620))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.grp_opciones.setFont(font)
        self.grp_opciones.setAlignment(QtCore.Qt.AlignCenter)
        self.grp_opciones.setObjectName("grp_opciones")
        self.bascula = QtWidgets.QPushButton(self.grp_opciones)
        self.bascula.setGeometry(QtCore.QRect(10, 30, 90, 90))
        self.bascula.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\static\\img\\bascula.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.bascula.setIcon(icon)
        self.bascula.setIconSize(QtCore.QSize(80, 80))
        self.bascula.setObjectName("bascula")
        self.reporte = QtWidgets.QPushButton(self.grp_opciones)
        self.reporte.setGeometry(QtCore.QRect(10, 121, 90, 90))
        self.reporte.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(".\\static\\img\\report.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.reporte.setIcon(icon1)
        self.reporte.setIconSize(QtCore.QSize(80, 80))
        self.reporte.setObjectName("reporte")
        self.cambiaclave = QtWidgets.QPushButton(self.grp_opciones)
        self.cambiaclave.setGeometry(QtCore.QRect(10, 513, 90, 30))
        self.cambiaclave.setFont(QtGui.QFont("Tahoma", 10))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(".\\static\\img\\recuperar.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.cambiaclave.setIcon(icon2)
        self.cambiaclave.setIconSize(QtCore.QSize(20, 20))
        self.cambiaclave.setObjectName("cambiaclave")
        self.salir = QtWidgets.QPushButton(self.grp_opciones)
        self.salir.setGeometry(QtCore.QRect(10, 584, 90, 30))
        self.salir.setFont(QtGui.QFont("Tahoma", 10))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(".\\static\\img\\salir.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.salir.setIcon(icon3)
        self.salir.setIconSize(QtCore.QSize(20, 20))
        self.salir.setObjectName("salir")
        self.cerrar = QtWidgets.QPushButton(self.grp_opciones)
        self.cerrar.setGeometry(QtCore.QRect(10, 545, 90, 30))
        self.cerrar.setFont(QtGui.QFont("Tahoma", 10))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(".\\static\\img\\cerrar.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.cerrar.setIcon(icon4)
        self.cerrar.setIconSize(QtCore.QSize(20, 20))
        self.cerrar.setObjectName("cerrar")
        self.frame = QtWidgets.QFrame(self.grp_opciones)
        self.frame.setGeometry(QtCore.QRect(10, 577, 90, 5))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setLineWidth(1)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 40, 901, 551))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(".\\static\\img\\background.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        frmPrincipal.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmPrincipal)
        QtCore.QMetaObject.connectSlotsByName(frmPrincipal)

    def retranslateUi(self, frmPrincipal):
        _translate = QtCore.QCoreApplication.translate
        frmPrincipal.setWindowTitle(_translate("frmPrincipal", "MainWindow"))
        self.grp_opciones.setTitle(_translate("frmPrincipal", " Opciones "))
        self.cambiaclave.setText(_translate("frmPrincipal", "C.Clave"))
        self.salir.setText(_translate("frmPrincipal", "Salir"))
        self.cerrar.setText(_translate("frmPrincipal", "Cerrar"))
