from sqlalchemy import create_engine, Column, Date, CHAR, Integer, String, Float, Date, DateTime, Text, Numeric
from sqlalchemy.dialects.oracle import VARCHAR2, NUMBER
from sqlalchemy.orm import declarative_base
import cx_Oracle
cx_Oracle.init_oracle_client(lib_dir=r"F:\\Python\\oracle\\instantclient_12_1_64")

Base = declarative_base()


class CaneMovim(Base):
    __tablename__ = "CANE_MOVIM"

    zafra = Column(NUMBER(4), primary_key=True)
    ingenio = Column(VARCHAR2(30), primary_key=True)
    cporte = Column(NUMBER(9), primary_key=True)
    cargadero = Column(VARCHAR2(30), nullable=False)
    fecha = Column(Date)
    orden_carga = Column(NUMBER(9))
    chofer = Column(VARCHAR2(240))
    fletero = Column(VARCHAR2(30))
    vehiculo = Column(VARCHAR2(240), nullable=False)
    remito = Column(VARCHAR2(240))
    descrip = Column(VARCHAR2(240))
    brix_leido = Column(NUMBER(4, 2))
    temperatura_leida = Column(NUMBER(2))
    brix = Column(NUMBER(4, 2))
    pol_leido = Column(NUMBER(4, 2))
    pol = Column(NUMBER(4, 2))
    polcana = Column(NUMBER(4, 2))
    coeficiente_trash = Column(NUMBER(7, 4))
    peso_torta_humeda = Column(NUMBER(9, 2))
    peso_torta_seca = Column(NUMBER(9, 2))
    trash = Column(NUMBER(9))
    trashpor = Column(NUMBER(7, 4))
    neto = Column(NUMBER(9))
    neto_primera = Column(NUMBER(9))
    tara = Column(NUMBER(9))
    bruto = Column(NUMBER(9))
    merma = Column(NUMBER(9))
    cadena = Column(NUMBER(9))
    cadena50 = Column(NUMBER(9))
    trapiche = Column(VARCHAR2(240), default='1')
    fecha_recepcion = Column(Date)
    uid_recepcion = Column(NUMBER(5))
    fecha_cosecha = Column(Date)
    uid_cosecha = Column(NUMBER(5))
    fecha_analisis = Column(Date)
    uid_analisis = Column(NUMBER(5))
    fecha_trash = Column(Date)
    uid_trash = Column(NUMBER(5))
    fecha_pesada = Column(Date)
    uid_pesada = Column(NUMBER(5))
    fecha_molienda = Column(Date)
    uid_molienda = Column(NUMBER(5))
    fecha_tara = Column(Date)
    uid_tara = Column(NUMBER(5))
    fecha_salida = Column(Date)
    uid_salida = Column(NUMBER(5))
    nrouid = Column(NUMBER(5), nullable=False)
    controla_trash = Column(CHAR(1), default='S')
    controla_tara = Column(CHAR(1), default='S')
    orden_llegada = Column(VARCHAR2(10))
    pureza = Column(NUMBER(5, 3))
    rendimiento = Column(NUMBER(5, 3))
    humedad = Column(NUMBER(6, 3))
    numero_muestra = Column(NUMBER(9))
    fecha_graba_analisis = Column(Date)
    trash_real = Column(NUMBER(7, 4))
    liquida_flete = Column(NUMBER(9))
    def_flete = Column(CHAR(1))
    fecha_liquida_flete = Column(Date)
    cantidad_carros = Column(NUMBER(4))
    fecha_muestra = Column(Date)
    feccar_muestra = Column(Date)
    transporte_muestra = Column(VARCHAR2(30))
    peso_torta_hum_sm = Column(NUMBER(9, 2))
    vehiculo_estadistico = Column(VARCHAR2(240))
    numero_cosechadora = Column(VARCHAR2(240))
    brix_original = Column(NUMBER(4, 2))
    pol_original = Column(NUMBER(4, 2))
    numero_liquida_flete = Column(NUMBER(9))
    sucursal_remito = Column(VARCHAR2(6))
    canero = Column(VARCHAR2(30))
    contrato = Column(VARCHAR2(30))
    usuario = Column(VARCHAR2(30))
    feccar = Column(Date)
    modulo = Column(VARCHAR2(240))
    host = Column(VARCHAR2(240))
    ip_address = Column(VARCHAR2(240))
    ingenio_carga = Column(VARCHAR2(30), default='1')
    balanza_bruto = Column(VARCHAR2(30))
    balanza_tara = Column(VARCHAR2(30))
    fk = Column(NUMBER(8, 4))
    numero_interno = Column(NUMBER(9))
    log_fecha = Column(Date)
    log_user = Column(VARCHAR2(30))
    log_host = Column(VARCHAR2(300))
    log_ip = Column(VARCHAR2(30))
    log_os = Column(VARCHAR2(300))
    fecmod = Column(Date)
    fecha_ticket_largada = Column(Date)

class CaneMovimRenglon(Base):
    __tablename__ = "CANE_MOVIM_RENGLON"

    azucar_exportacion = Column(NUMBER(9, 2))
    azucar_normal = Column(NUMBER(9, 2))
    zafra = Column(NUMBER(4), primary_key=True)
    cporte = Column(NUMBER(9), primary_key=True)
    renglon = Column(NUMBER(9), primary_key=True)
    fecha = Column(Date, nullable=True)
    cargadero = Column(VARCHAR2(30), nullable=False)
    canero = Column(VARCHAR2(240), nullable=False)
    contrato = Column(VARCHAR2(30), nullable=False)
    origen = Column(VARCHAR2(240), nullable=False)
    finca = Column(VARCHAR2(30))
    variedad = Column(VARCHAR2(30))
    cooperativa = Column(VARCHAR2(30))
    neto_primera = Column(NUMBER(6))
    cana_neta = Column(NUMBER(6))
    neto = Column(NUMBER(6))
    trash = Column(NUMBER(9))
    trashpor = Column(NUMBER(7, 4))
    brix = Column(NUMBER(4, 2), default=0)
    pol = Column(NUMBER(4, 2), default=0)
    pol_cana = Column(NUMBER(5, 3), default=0)
    pureza = Column(NUMBER(5, 3))
    rendimiento = Column(NUMBER(5, 3))
    cortador = Column(VARCHAR2(30))
    cosechador = Column(VARCHAR2(30))
    cargador = Column(VARCHAR2(30))
    cuartero = Column(VARCHAR2(30))
    azucar = Column(NUMBER(9, 2))
    azucar_real = Column(NUMBER(9, 2))
    azucar_canero = Column(NUMBER(9, 2))
    liquida_maq = Column(NUMBER(9))
    liquida_con = Column(NUMBER(9))
    liquida_fle = Column(NUMBER(9))
    liquida_car = Column(NUMBER)
    liquida_cor = Column(NUMBER)
    liquida_cos = Column(NUMBER)
    liquida_cua = Column(NUMBER)
    def_maq = Column(VARCHAR2(2))
    def_con = Column(VARCHAR2(2))
    def_fle = Column(VARCHAR2(2))
    def_car = Column(VARCHAR2(2))
    def_cor = Column(VARCHAR2(2))
    def_cos = Column(VARCHAR2(2))
    def_cua = Column(VARCHAR2(2))
    nrouid = Column(NUMBER(5), nullable=False)
    tipo_cosecha = Column(VARCHAR2(4), nullable=False)
    tipo_cana = Column(VARCHAR2(4), nullable=False)
    fecha_analisis = Column(Date)
    humedad = Column(NUMBER(6, 3))
    trash_real = Column(NUMBER(7, 4))
    fibra = Column(NUMBER(6))
    fibrapor = Column(NUMBER(7, 4))
    azucar_servicios = Column(NUMBER(9, 2))
    fecha_liquida_maq = Column(Date)
    fecha_liquida_con = Column(Date)
    fecha_liquida_fle = Column(Date)
    fecha_liquida_car = Column(Date)
    fecha_liquida_cor = Column(Date)
    fecha_liquida_cos = Column(Date)
    fecha_liquida_cua = Column(Date)
    comprobante = Column(NUMBER(8))
    centro_facturacion = Column(NUMBER(4))
    edad = Column(VARCHAR2(30))
    brix_original = Column(NUMBER(4, 2))
    pol_original = Column(NUMBER(4, 2))
    brix_leido_original = Column(NUMBER(4, 2))
    pol_leido_original = Column(NUMBER(4, 2))
    rendimiento_original = Column(NUMBER(5, 3))
    nrousr_mod_original = Column(NUMBER(6))
    fecha_cambio_original = Column(Date)
    azucar_minimo = Column(NUMBER(9, 2))
    numero_liquida_cos = Column(VARCHAR2(240))
    numero_liquida_car = Column(VARCHAR2(240))
    numero_liquida_cua = Column(VARCHAR2(240))
    numero_liquida_cor = Column(VARCHAR2(240))
    ingenio = Column(VARCHAR2(30), nullable=False, default='1')
    usuario = Column(VARCHAR2(30))
    feccar = Column(Date)
    modulo = Column(VARCHAR2(240))
    host = Column(VARCHAR2(240))
    ip_address = Column(VARCHAR2(240))
    ultimo_neto = Column(NUMBER(12, 2))
    fk = Column(NUMBER(8, 4))
    sucursal_rem = Column(NUMBER(4))
    numcomp_rem = Column(NUMBER(8))
    log_fecha = Column(Date)
    log_user = Column(VARCHAR2(30))
    log_host = Column(VARCHAR2(300))
    log_ip = Column(VARCHAR2(30))
    log_os = Column(VARCHAR2(300))
    fecmod = Column(Date)

class CaneMovimPeso(Base):
    __tablename__ = "CANE_MOVIM_PESO"

    zafra = Column(NUMBER(4), primary_key=True)
    ingenio = Column(VARCHAR2(30), primary_key=True, default='1')
    cporte = Column(NUMBER(9), primary_key=True)
    renglon = Column(NUMBER(4), primary_key=True)
    bruto = Column(NUMBER(9), nullable=False)
    tara = Column(NUMBER(9))
    nrouid = Column(NUMBER(5))
    feccar = Column(Date)
    usuario = Column(VARCHAR2(30))

class CanePesosBalanza(Base):
    __tablename__ = "CANE_PESOS_BALANZA_W"
    __table_args__ = {"info": {"is_view": True}}

    zafra = Column(NUMBER(4), primary_key=True)
    cporte = Column(NUMBER(9), primary_key=True)
    tara = Column(VARCHAR2(1))
    vehiculo = Column(VARCHAR2(240))
    chofer = Column(VARCHAR2(240))
    cargadero = Column(VARCHAR2(240))
    descrip = Column(VARCHAR2(240))
    fecha_recepcion = Column(Date)
    hora = Column(VARCHAR2(240))
    balanza_bruto = Column(VARCHAR2(40))

class CaneBalanzaInfo(Base): 
    __tablename__ = "CANE_BALANZA_INFO_W"
    __table_args__ = {"info": {"is_view": True}}

    zafra = Column(NUMBER(4), primary_key=True)
    cporte = Column(NUMBER(9), primary_key=True)
    tipo_cosecha = Column(VARCHAR2(4))
    desc_tipocosecha = Column(VARCHAR2(240))
    cosechador = Column(VARCHAR2(30))
    tipo_cana = Column(VARCHAR2(4))
    desc_tipocana = Column(VARCHAR2(240))
    fletero = Column(VARCHAR2(30))
    cargadero = Column(VARCHAR2(30))
    canero = Column(VARCHAR2(240))
    contrato = Column(VARCHAR2(30))
    suc_rto = Column(NUMBER(4))
    nro_rto = Column(NUMBER(8))
    bruto = Column(NUMBER(9))
    tara = Column(NUMBER(9))
    cana_bruta = Column(NUMBER(9))
    trashpor = Column(NUMBER(7, 4))
    trash = Column(NUMBER(9))
    neto = Column(NUMBER(9))

class CaneCanero(Base):
    __tablename__ = 'cane_canero'
    canero = Column(String(240), primary_key=True)
    descrip = Column(String(240))
    domicilio = Column(String(240))
    tipdoc = Column(String(240))
    cuit = Column(String(13))
    ingbrutos = Column(String(13))
    tipoiva = Column(Integer)
    apoderado = Column(String(240))
    grupo = Column(String(30))
    incripcion = Column(String(240))
    contrato = Column(Integer)
    nrousr = Column(Integer)
    nrogrp = Column(Integer)
    permiso = Column(Integer)
    nrouid = Column(Integer)
    ultima_minuta = Column(Integer)
    winter = Column(Numeric(9,8))
    cupo = Column(Integer)
    grupo_gerencia = Column(String(30))
    cpostal = Column(String(30))
    feccar = Column(Date)
    usuario = Column(String(30))
    total_kilos = Column(Integer)
    log_fecha = Column(Date)
    log_user = Column(String(30))
    log_host = Column(String(300))
    log_ip = Column(String(30))
    log_os = Column(String(300))
    fecmod = Column(Date)

class Cane_Fletero(Base):
    __tablename__ = 'cane_fletero'
    codigo = Column(String(30), primary_key=True)
    descrip = Column(String(240))
    tipsub = Column(Integer)
    nrosub = Column(Integer)
    tarifa_canero = Column(Integer)
    tarifa_fletero = Column(Integer)
    nrocta = Column(Integer)
    cosechadora = Column(String(240))

class Cane_Vehiculos(Base):
    __tablename__ = 'cane_vehiculos'
    codigo = Column(String(240), primary_key=True)
    descrip = Column(String(240))
    tipo_vehiculo = Column(String(2))
    fletero = Column(String(30))
    tipsub = Column(Integer)
    nrosub = Column(Integer)
    tara = Column(Integer)
    patente = Column(String(240))
    atc = Column(String(240))
    arranque = Column(Numeric(12,2))
    pavimento = Column(Numeric(12,2))
    ripio = Column(Numeric(12,2))
    nrouid = Column(Integer)
    fecha_tara = Column(Date)
    fecha_carga_tren = Column(Date)
    tarifa_fletero = Column(Integer)
    tarifa_canero = Column(Integer)
    cosechadora = Column(String(240))
    capacidad = Column(Integer)
    control_recep = Column(String(1))
    control_tiempo = Column(Numeric(12,2))

class CaneBalanzaHora(Base):
    __tablename__ = 'cane_balanza_hora_w'
    hora = Column(String(2), primary_key=True)
    hora_real = Column(Float)
    bruto = Column(Float)
    ktrash = Column(Float)
    neto = Column(Float)

def get_engine(user, password, host, port, service_name):
    # Retorna un engine de conexión a Oracle
    return create_engine(
        f"oracle+cx_oracle://{user}:{password}@{host}:{port}/?service_name={service_name}",
        echo=False
    )
